"""
@Author: Rohan Vetale

@Date: 2024-01-28 12:40

@Last Modified by: Rohan Vetale

@Last Modified time: 2024-01-28 19:23

@Title : Fundoo Notes user module
"""
from sqlalchemy.exc import IntegrityError
from fastapi import APIRouter, Depends, status, Response, HTTPException
from sqlalchemy.orm import Session
from core.model import User, get_db
from core.schema import UserDetails, Userlogin
from passlib.hash import sha256_crypt

router_user = APIRouter()



@router_user.post("/post", status_code=status.HTTP_201_CREATED)
def user_registration(body: UserDetails, response: Response, db: Session = Depends(get_db)):
    """
    Description: This function create api for adding a new user.
    Parameter: body as UserDetails object, response as Response object, db as database session.
    Return: Message of user data added with status code 201.
    """
    try:
        user_data = body.model_dump()
        user_data['password'] = sha256_crypt.hash(user_data['password'])
        new_user = User(**user_data)
        db.add(new_user)
        db.commit()
        db.refresh(new_user)
        return {"status": 201, "message": "Registered successfully", 'data': new_user}
    except Exception as e:
        response.status_code = 400
        print(e)
        return {"message": str(e), 'status': 400}


@router_user.post("/login", status_code=status.HTTP_200_OK)
def user_login(payload: Userlogin, response: Response, db: Session = Depends(get_db)):
    """
    Description: This function create api for login the user.
    Parameter: payload as Userlogin object, response as Response object, db as database session.
    Return: Message of user login with status code 201 and token generated by jwt header.
    """
    try:
        user = db.query(User).filter_by(user_name=payload.user_name).first()
        if user and sha256_crypt.verify(payload.password, user.password):
            return {'status': 200, "message": 'Logged in successfully'}
        else:
            response.status_code = status.HTTP_401_UNAUTHORIZED
            return {"message": 'Invalid username, password, or user not verified', 'status': 401}
    
    except Exception as e:
        response.status_code = 400
        return {"message": str(e), 'status': 400}