"""inherited labels

Revision ID: 4e852c4068be
Revises: 0ba927af48ab
Create Date: 2024-02-02 10:17:42.093664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e852c4068be'
down_revision: Union[str, None] = '0ba927af48ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('label_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_id'), 'label', ['id'], unique=False)
    op.drop_index('ix_labels_id', table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('label_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='labels_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='labels_pkey'),
    sa.UniqueConstraint('label_name', name='labels_label_name_key')
    )
    op.create_index('ix_labels_id', 'labels', ['id'], unique=False)
    op.drop_index(op.f('ix_label_id'), table_name='label')
    op.drop_table('label')
    # ### end Alembic commands ###
